name: Deploy to Azure Function App

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests # Replace with your actual dependencies

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: . # Set this to the path of your code or build output

    - name: 'Finish Deployment'
      run: echo "Deployment to ${AZURE_FUNCTIONAPP_NAME} successful!"
